[DEFAULT]
modelo = gpt-4o-mini
#modelo = gpt-4o



cohere_api_key = tu-clave-cohere


[CARGA_EXTERNA]
chunk_size_padre = 2000
chunk_size_hijo = 400

max_results = 25


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Esto es donde y como se va llamar la BDV

FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\CARGA_TXT\EXTERNA\BDV
FRAGMENT_STORE_DIR1211 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODO

collection_name_fragmento = fragment_store

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_FRAGMENTOS_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\EXTERNA\
LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\EXTERNA\

# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE =lista_externa_txt.txt
LISTA_PDF_RESUMEN_FILE =lista_resoluciones_resumen.txt

FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\EXTERNA\
RESUMEN_DIR  =C:\Users\u14527001\Downloads\regra\CARGA_TXT\EXTERNA\







[CARGA_TODO]
chunk_size_padre = 2000
chunk_size_hijo = 400

max_results = 15


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Esto es donde y como se va llamar la BDV

FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\BDV_3

collection_name_fragmento = fragment_store


SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_FRAGMENTOS_DIR = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\
LISTA_PDF_RESUMEN_DIR = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\

# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE = toda_3.txt
LISTA_PDF_RESUMEN_FILE =lista_resoluciones_resumen.txt

FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\

[BOLETIN]
chunk_size_padre = 2000
chunk_size_hijo = 400
fecha_desde = 2024-09-05
fecha_hasta =  2024-12-10


max_results = 50


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'
#Esto es donde y como se va llamar la BDV

FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V10
# CREO QUE TODO  NOSE
FRAGMENT_STORE_DIREW = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V4

collection_name_fragmento = fragment_store


SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_FRAGMENTOS_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\

# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE =lista_resoluciones.txt
LISTA_PDF_RESUMEN_FILE =lista_resoluciones_resumen.txt

FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\



[CARGA_RESOLUCIONES]
chunk_size_padre = 2000
chunk_size_hijo = 400
fecha_desde = 2024-12-01
fecha_hasta =  2024-12-10


max_results = 45


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'
#Esto es donde y como se va llamar la BDV
FRAGMENT_STORE_DIR653 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_2562
FRAGMENT_STORE_DIR009 = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V1

FRAGMENT_STORE_DIR3332 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_15
#SOLO RESOLUCIONES
FRAGMENT_STORE_DIR331 = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_fragment_store_c

FRAGMENT_STORE_DIR33 = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V10
# CREO QUE TODO  NOSE
FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V4
FRAGMENT_STORE_DIR33334 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_fragment_store_g

### LE PUSE TODO 
FRAGMENT_STORE_DIR_34333 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODA\BDV_3


FRAGMENT_STORE_DIR_3433 = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_fragment_store_c
FRAGMENT_STORE_DIR_SS = C:\Users\u14527001\Downloads\regra\CARGA_TXT\INSTRUCTIVO\BDV\chroma_fragment_store_b
FRAGMENT_STORE_DIRdff = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODO

FRAGMENT_STORE_DIR_V4 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_fragment_store_g
collection_name_fragmento = fragment_store


SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_FRAGMENTOS_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\

# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE =lista_resoluciones.txt
LISTA_PDF_RESUMEN_FILE =lista_resoluciones_resumen.txt

FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\


[CARGA_RESOLUCIONES_PDF]
chunk_size_padre = 2000
chunk_size_hijo = 500
chunk_overlap = 50

max_results = 15

tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Direcotrio donde esta el archivo de la lista de archivos
LISTA_PDF_FRAGMENTOS_DIR = C:\Users\u14527001\Downloads\regra
#NOMBRE DEL ARCHIVO DE LA LISTA DE ARCHIVOS
LISTA_PDF_FRAGMENTOS_FILE= lista_boleto1.txt


#CARPETA DONDE ESTAN LOS ARCHIVOS PDF
FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\BOLETIN\

#CARPETA Y NOMBRE DE LA BDV
FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V10

collection_name_fragmento = fragment_store



[CARGA_RESOLUCIONES_TXT]
chunk_size_padre = 2000
chunk_size_hijo = 500
chunk_overlap = 50

max_results = 15


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Esto es donde y como se va llamar la BDV


#Direcotrio donde esta el archivo de la lista de archivos
FRAGMENTO_DIR  = C:\Users\u14527001\Downloads\regra\BOLETIN

LISTA_PDF_FRAGMENTOS_DIR =  C:\Users\u14527001\Downloads\regra
LISTA_PDF_FRAGMENTOS_FILE =lista_boleto1_txt.txt

FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V7





FRAGMENT_STORE_DIR66 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_boleto

FRAGMENT_STORE_DIR77 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_2562
FRAGMENT_STORE_DIR888 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_15
collection_name_fragmento = fragment_store



FRAGMENT_STORE_DIR_333 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_fragment_store_g
FRAGMENT_STORE_DIRfdfd = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODO


SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\
#TEST SOLO ARCHIVOS DE TEST
# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt


FRAGMENTO_DIR1111 =C:\Users\u14527001\Downloads\regra\CARGA_TXT
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\CARGA_TXT\



[CARGA_INSTRUCTIVO]
chunk_size_padre = 2000
chunk_size_hijo = 500
chunk_overlap = 50

max_results = 45


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Esto es donde y como se va llamar la BDV
LISTA_PDF_FRAGMENTOS_FILE = lista_resoluciones_test_15.txt

FRAGMENT_STORE_DIR2122 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_2562

FRAGMENT_STORE_DIRwe = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V1
FRAGMENT_STORE_DIR22244 = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V4
FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V10

FRAGMENT_STORE_DIR232  = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_fragment_store_g

FRAGMENT_STORE_DIR444 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_resoluciones_TEST_15

collection_name_fragmento = fragment_store
LISTA_PDF_FRAGMENTOS_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\


FRAGMENT_STORE_DIR_333 = C:\Users\u14527001\Downloads\regra\CARGA_TXT\chroma_fragment_store_g
FRAGMENT_STORE_DIRfdfd = C:\Users\u14527001\Downloads\regra\CARGA_TXT\TODO

SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\

#TEST SOLO ARCHIVOS DE TEST


# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE3333 =lista_resoluciones.txt




FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\CARGA_TXT\
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\CARGA_TXT\




[CARGA_RESOLUCIONES_RESUMEN]
chunk_size_padre = 2000
chunk_size_hijo = 400

max_results = 15


tipo_retrieve = mmr  ; puede ser 'similitud' o 'mmr'

#Esto es donde y como se va llamar la BDV
FRAGMENT_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_fragmento = summary_store
SUMMARY_STORE_DIR = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\BDV\chroma_summary_store_c
collection_name_summary = summary_store
# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc

# /archivo/ --->  directorio donde estan los archivos pdf reso-23232.pdf, reso-34e343.pdf,etc
LISTA_PDF_FRAGMENTOS_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
LISTA_PDF_RESUMEN_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\

# /archivo/lista_resoluticiones.txt 1) /archivo  2)lista_resoluciones.txt
LISTA_PDF_FRAGMENTOS_FILE =lista_resoluciones.txt
LISTA_PDF_RESUMEN_FILE =lista_resoluciones_resumen.txt

FRAGMENTO_DIR =C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\
RESUMEN_DIR  = C:\Users\u14527001\Downloads\regra\DATOS\RESOLUCIONES\ARCHIVOS\

#SIMAP 
[NOTICIAS]
fecha_desde = 2024-02-08
fecha_hasta = 2024-12-10
max_results = 45

#directorio_bdvectorial = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V2
#colleciontion name 
nombre_bdvectorial = fragment_store
FRAGMENT_STORE_DIR =  C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\V4

FRAGMENT_STORE_DIR434 = C:\Users\u14527001\Downloads\regra\BOLETIN\BDV\V10


#nombre del archivo json
nombre_archivo_json = Novedades_SIMAP.json
directorio_archivo_json = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\ARCHIVOS


directorio_bdvectorial = C:\Users\u14527001\Downloads\regra\DATOS\NOTICIAS\BDV\

collection_name_fragmento = mi_coleccion_json


tamano_chunk = 300
overlap_chunk = 50

[SERVICIOS_SIMAP]
fecha_desde = 2024-02-08
fecha_hasta = 2024-12-10
max_results = 20




nombre_bdvectorial = fragment_store
#FRAGMENT_STORE_DIR =  C:\Users\u14527001\Downloads\regra\DATOS\SERVICIOS\BDV\SERVICIOS_9_1000

#Esto WINDOWS
#FRAGMENT_STORE_DIR =  data\SERVICIOS\SERVICIOS_b_2
#C:\Users\u14527001\Downloads\regra\DATOS\SERVICIOS\BDV\SERVICIOS_b_2

#Formato DOCKER
FRAGMENT_STORE_DIR =  data/SERVICIOS/SERVICIOS_b_2


tamano_chunk = 300
overlap_chunk = 50
max_context_tokens = 80

#nombre del archivo json
#nombre_archivo_json = Prueba.json


collection_name_fragmento = fragment_store



