
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # solo para entornos DEV 
      - HTTP_PROXY=http://10.100.115.253:8080
      - HTTPS_PROXY=http://10.100.115.253:8080
      - http_proxy=http://10.100.115.253:8080
      - https_proxy=http://10.100.115.253:8080   

    image: asis-virtual-simap # <- Nombre de la imagen, si está definido

